// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvqquymbjuisboefquev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2cXF1eW1ianVpc2JvZWZxdWV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTc0NTQsImV4cCI6MjA3MTk3MzQ1NH0.-ab4gkB491aOKyVnp6-dN_sLpngllmHJ24I4nRSiOZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});